apiVersion: v1
kind: Service
metadata:
  name:  suneer-rtp-service
  namespace: suneer
spec:
  type: NodePort
  selector:
    app: suneer-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
